# Generated by Django 3.2.25 on 2024-05-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerenquiry',
            name='enquiry',
            field=models.TextField(default=''),
        ),
    ]
