# Generated by Django 3.2.25 on 2024-05-06 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_enquiries', '0002_alter_customerenquiry_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerenquiry',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
