# Generated by Django 3.2.25 on 2024-04-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_available_in_hardback'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_pages',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
